<?php

namespace App\Http\Requests\Api;

class ReplyRequest extends FormRequest
{
    /**
     * @return bool
     */
    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }

    /**
     * 回复字符规则
     * @return array
     */
    public function rules()
    {
        return [
            'content' => 'required|min:2',
        ];
    }
}
